/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing ApiErrorDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiErrorDTOTests
    {
        // TODO uncomment below to declare an instance variable for ApiErrorDTO
        //private ApiErrorDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiErrorDTO
            //instance = new ApiErrorDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiErrorDTO
        /// </summary>
        [Test]
        public void ApiErrorDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiErrorDTO
            //Assert.IsInstanceOfType<ApiErrorDTO> (instance, "variable 'instance' is a ApiErrorDTO");
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
