/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing CarrierAdvancedOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CarrierAdvancedOptionTests
    {
        // TODO uncomment below to declare an instance variable for CarrierAdvancedOption
        //private CarrierAdvancedOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierAdvancedOption
            //instance = new CarrierAdvancedOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierAdvancedOption
        /// </summary>
        [Test]
        public void CarrierAdvancedOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CarrierAdvancedOption
            //Assert.IsInstanceOfType<CarrierAdvancedOption> (instance, "variable 'instance' is a CarrierAdvancedOption");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Test]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
