/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing CreateShipmentsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateShipmentsRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateShipmentsRequest
        //private CreateShipmentsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateShipmentsRequest
            //instance = new CreateShipmentsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateShipmentsRequest
        /// </summary>
        [Test]
        public void CreateShipmentsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateShipmentsRequest
            //Assert.IsInstanceOfType<CreateShipmentsRequest> (instance, "variable 'instance' is a CreateShipmentsRequest");
        }

        /// <summary>
        /// Test the property 'Shipments'
        /// </summary>
        [Test]
        public void ShipmentsTest()
        {
            // TODO unit test for the property 'Shipments'
        }

    }

}
