/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing PurchaseLabelWithoutShipmentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PurchaseLabelWithoutShipmentRequestTests
    {
        // TODO uncomment below to declare an instance variable for PurchaseLabelWithoutShipmentRequest
        //private PurchaseLabelWithoutShipmentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PurchaseLabelWithoutShipmentRequest
            //instance = new PurchaseLabelWithoutShipmentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PurchaseLabelWithoutShipmentRequest
        /// </summary>
        [Test]
        public void PurchaseLabelWithoutShipmentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PurchaseLabelWithoutShipmentRequest
            //Assert.IsInstanceOfType<PurchaseLabelWithoutShipmentRequest> (instance, "variable 'instance' is a PurchaseLabelWithoutShipmentRequest");
        }

        /// <summary>
        /// Test the property 'LabelFormat'
        /// </summary>
        [Test]
        public void LabelFormatTest()
        {
            // TODO unit test for the property 'LabelFormat'
        }
        /// <summary>
        /// Test the property 'LabelLayout'
        /// </summary>
        [Test]
        public void LabelLayoutTest()
        {
            // TODO unit test for the property 'LabelLayout'
        }
        /// <summary>
        /// Test the property 'TestLabel'
        /// </summary>
        [Test]
        public void TestLabelTest()
        {
            // TODO unit test for the property 'TestLabel'
        }
        /// <summary>
        /// Test the property 'ValidateAddress'
        /// </summary>
        [Test]
        public void ValidateAddressTest()
        {
            // TODO unit test for the property 'ValidateAddress'
        }

    }

}
