/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    ///     ApiErrorResponseDTO
    /// </summary>
    [DataContract]
    public class ApiErrorResponseDTO : IEquatable<ApiErrorResponseDTO>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="ApiErrorResponseDTO" /> class.
        /// </summary>
        /// <param name="requestId">RequestId.</param>
        /// <param name="errors">Errors.</param>
        public ApiErrorResponseDTO(Guid? requestId = default(Guid?),
            List<ApiErrorDTO> errors = default(List<ApiErrorDTO>))
        {
            RequestId = requestId;
            Errors = errors;
        }

        /// <summary>
        ///     Gets or Sets RequestId
        /// </summary>
        [DataMember(Name = "request_id", EmitDefaultValue = false)]
        public Guid? RequestId { get; set; }

        /// <summary>
        ///     Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<ApiErrorDTO> Errors { get; set; }

        /// <summary>
        ///     Returns true if ApiErrorResponseDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of ApiErrorResponseDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiErrorResponseDTO other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
            {
                return false;
            }

            return
                (
                    RequestId == other.RequestId ||
                    RequestId != null &&
                    RequestId.Equals(other.RequestId)
                ) &&
                (
                    Errors == other.Errors ||
                    Errors != null &&
                    Errors.SequenceEqual(other.Errors)
                );
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiErrorResponseDTO {\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as ApiErrorResponseDTO);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (RequestId != null)
                {
                    hash = hash * 59 + RequestId.GetHashCode();
                }
                if (Errors != null)
                {
                    hash = hash * 59 + Errors.GetHashCode();
                }
                return hash;
            }
        }
    }
}