/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    ///     CarrierListServicesResponse
    /// </summary>
    [DataContract]
    public class CarrierListServicesResponse : IEquatable<CarrierListServicesResponse>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="CarrierListServicesResponse" /> class.
        /// </summary>
        /// <param name="services">Services.</param>
        public CarrierListServicesResponse(List<Service> services = default(List<Service>))
        {
            Services = services;
        }

        /// <summary>
        ///     Gets or Sets Services
        /// </summary>
        [DataMember(Name = "services", EmitDefaultValue = false)]
        public List<Service> Services { get; set; }

        /// <summary>
        ///     Returns true if CarrierListServicesResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CarrierListServicesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CarrierListServicesResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
            {
                return false;
            }

            return
                Services == other.Services ||
                Services != null &&
                Services.SequenceEqual(other.Services);
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CarrierListServicesResponse {\n");
            sb.Append("  Services: ").Append(Services).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as CarrierListServicesResponse);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Services != null)
                {
                    hash = hash * 59 + Services.GetHashCode();
                }
                return hash;
            }
        }
    }
}