/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ShipEngine.ApiClient.Client.SwaggerDateConverter;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    /// CreateBatchRequest
    /// </summary>
    [DataContract]
    public partial class CreateBatchRequest :  IEquatable<CreateBatchRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBatchRequest" /> class.
        /// </summary>
        /// <param name="ExternalBatchId">ExternalBatchId.</param>
        /// <param name="BatchNotes">BatchNotes.</param>
        /// <param name="ShipmentIds">ShipmentIds.</param>
        /// <param name="RateIds">RateIds.</param>
        public CreateBatchRequest(string ExternalBatchId = default(string), string BatchNotes = default(string), List<string> ShipmentIds = default(List<string>), List<string> RateIds = default(List<string>))
        {
            this.ExternalBatchId = ExternalBatchId;
            this.BatchNotes = BatchNotes;
            this.ShipmentIds = ShipmentIds;
            this.RateIds = RateIds;
        }
        
        /// <summary>
        /// Gets or Sets ExternalBatchId
        /// </summary>
        [DataMember(Name="external_batch_id", EmitDefaultValue=false)]
        public string ExternalBatchId { get; set; }

        /// <summary>
        /// Gets or Sets BatchNotes
        /// </summary>
        [DataMember(Name="batch_notes", EmitDefaultValue=false)]
        public string BatchNotes { get; set; }

        /// <summary>
        /// Gets or Sets ShipmentIds
        /// </summary>
        [DataMember(Name="shipment_ids", EmitDefaultValue=false)]
        public List<string> ShipmentIds { get; set; }

        /// <summary>
        /// Gets or Sets RateIds
        /// </summary>
        [DataMember(Name="rate_ids", EmitDefaultValue=false)]
        public List<string> RateIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateBatchRequest {\n");
            sb.Append("  ExternalBatchId: ").Append(ExternalBatchId).Append("\n");
            sb.Append("  BatchNotes: ").Append(BatchNotes).Append("\n");
            sb.Append("  ShipmentIds: ").Append(ShipmentIds).Append("\n");
            sb.Append("  RateIds: ").Append(RateIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateBatchRequest);
        }

        /// <summary>
        /// Returns true if CreateBatchRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateBatchRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateBatchRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ExternalBatchId == input.ExternalBatchId ||
                    (this.ExternalBatchId != null &&
                    this.ExternalBatchId.Equals(input.ExternalBatchId))
                ) && 
                (
                    this.BatchNotes == input.BatchNotes ||
                    (this.BatchNotes != null &&
                    this.BatchNotes.Equals(input.BatchNotes))
                ) && 
                (
                    this.ShipmentIds == input.ShipmentIds ||
                    this.ShipmentIds != null &&
                    this.ShipmentIds.SequenceEqual(input.ShipmentIds)
                ) && 
                (
                    this.RateIds == input.RateIds ||
                    this.RateIds != null &&
                    this.RateIds.SequenceEqual(input.RateIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExternalBatchId != null)
                    hashCode = hashCode * 59 + this.ExternalBatchId.GetHashCode();
                if (this.BatchNotes != null)
                    hashCode = hashCode * 59 + this.BatchNotes.GetHashCode();
                if (this.ShipmentIds != null)
                    hashCode = hashCode * 59 + this.ShipmentIds.GetHashCode();
                if (this.RateIds != null)
                    hashCode = hashCode * 59 + this.RateIds.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
