/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ShipEngine.ApiClient.Client.SwaggerDateConverter;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    /// CreateWebhookDTO
    /// </summary>
    [DataContract]
    public partial class CreateWebhookDTO :  IEquatable<CreateWebhookDTO>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets _Event
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventEnum
        {
            
            /// <summary>
            /// Enum Rate for "rate"
            /// </summary>
            [EnumMember(Value = "rate")]
            Rate = 1,
            
            /// <summary>
            /// Enum Track for "track"
            /// </summary>
            [EnumMember(Value = "track")]
            Track = 2,
            
            /// <summary>
            /// Enum Batch for "batch"
            /// </summary>
            [EnumMember(Value = "batch")]
            Batch = 3
        }

        /// <summary>
        /// Gets or Sets _Event
        /// </summary>
        [DataMember(Name="event", EmitDefaultValue=false)]
        public EventEnum? _Event { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateWebhookDTO" /> class.
        /// </summary>
        /// <param name="_Event">_Event.</param>
        /// <param name="Url">Url.</param>
        public CreateWebhookDTO(EventEnum? _Event = default(EventEnum?), string Url = default(string))
        {
            this._Event = _Event;
            this.Url = Url;
        }
        

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateWebhookDTO {\n");
            sb.Append("  _Event: ").Append(_Event).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateWebhookDTO);
        }

        /// <summary>
        /// Returns true if CreateWebhookDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateWebhookDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateWebhookDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Event == input._Event ||
                    (this._Event != null &&
                    this._Event.Equals(input._Event))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Event != null)
                    hashCode = hashCode * 59 + this._Event.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
