/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    ///     ListTagResponse
    /// </summary>
    [DataContract]
    public class ListTagResponse : IEquatable<ListTagResponse>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="ListTagResponse" /> class.
        /// </summary>
        /// <param name="tags">Tags.</param>
        public ListTagResponse(List<TagResponse> tags = default(List<TagResponse>))
        {
            Tags = tags;
        }

        /// <summary>
        ///     Tags
        /// </summary>
        /// <value>Tags</value>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<TagResponse> Tags { get; set; }

        /// <summary>
        ///     Returns true if ListTagResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ListTagResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListTagResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
            {
                return false;
            }

            return
                Tags == other.Tags ||
                Tags != null &&
                Tags.SequenceEqual(other.Tags);
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListTagResponse {\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as ListTagResponse);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Tags != null)
                {
                    hash = hash * 59 + Tags.GetHashCode();
                }
                return hash;
            }
        }
    }
}