/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ShipEngine.ApiClient.Client.SwaggerDateConverter;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    /// ModifyBatchRequest
    /// </summary>
    [DataContract]
    public partial class ModifyBatchRequest :  IEquatable<ModifyBatchRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyBatchRequest" /> class.
        /// </summary>
        /// <param name="ShipmentIds">ShipmentIds.</param>
        /// <param name="RateIds">RateIds.</param>
        public ModifyBatchRequest(List<string> ShipmentIds = default(List<string>), List<string> RateIds = default(List<string>))
        {
            this.ShipmentIds = ShipmentIds;
            this.RateIds = RateIds;
        }
        
        /// <summary>
        /// Gets or Sets ShipmentIds
        /// </summary>
        [DataMember(Name="shipment_ids", EmitDefaultValue=false)]
        public List<string> ShipmentIds { get; set; }

        /// <summary>
        /// Gets or Sets RateIds
        /// </summary>
        [DataMember(Name="rate_ids", EmitDefaultValue=false)]
        public List<string> RateIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModifyBatchRequest {\n");
            sb.Append("  ShipmentIds: ").Append(ShipmentIds).Append("\n");
            sb.Append("  RateIds: ").Append(RateIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModifyBatchRequest);
        }

        /// <summary>
        /// Returns true if ModifyBatchRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ModifyBatchRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModifyBatchRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipmentIds == input.ShipmentIds ||
                    this.ShipmentIds != null &&
                    this.ShipmentIds.SequenceEqual(input.ShipmentIds)
                ) && 
                (
                    this.RateIds == input.RateIds ||
                    this.RateIds != null &&
                    this.RateIds.SequenceEqual(input.RateIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipmentIds != null)
                    hashCode = hashCode * 59 + this.ShipmentIds.GetHashCode();
                if (this.RateIds != null)
                    hashCode = hashCode * 59 + this.RateIds.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
