/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    ///     RateShipmentsRequest
    /// </summary>
    [DataContract]
    public class RateShipmentsRequest : IEquatable<RateShipmentsRequest>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RateShipmentsRequest" /> class.
        /// </summary>
        /// <param name="shipmentIds">ShipmentIds.</param>
        /// <param name="rateOptions">RateOptions.</param>
        /// <param name="shipments">Shipments.</param>
        public RateShipmentsRequest(List<string> shipmentIds = default(List<string>),
            RateRequest rateOptions = default(RateRequest),
            List<AddressValidatingShipment> shipments = default(List<AddressValidatingShipment>))
        {
            ShipmentIds = shipmentIds;
            RateOptions = rateOptions;
            Shipments = shipments;
        }

        /// <summary>
        ///     Gets or Sets ShipmentIds
        /// </summary>
        [DataMember(Name = "shipment_ids", EmitDefaultValue = false)]
        public List<string> ShipmentIds { get; set; }

        /// <summary>
        ///     Gets or Sets RateOptions
        /// </summary>
        [DataMember(Name = "rate_options", EmitDefaultValue = false)]
        public RateRequest RateOptions { get; set; }

        /// <summary>
        ///     Gets or Sets Shipments
        /// </summary>
        [DataMember(Name = "shipments", EmitDefaultValue = false)]
        public List<AddressValidatingShipment> Shipments { get; set; }

        /// <summary>
        ///     Returns true if RateShipmentsRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of RateShipmentsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RateShipmentsRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
            {
                return false;
            }

            return
                (
                    ShipmentIds == other.ShipmentIds ||
                    ShipmentIds != null &&
                    ShipmentIds.SequenceEqual(other.ShipmentIds)
                ) &&
                (
                    Equals(RateOptions, other.RateOptions) ||
                    RateOptions != null &&
                    RateOptions.Equals(other.RateOptions)
                ) &&
                (
                    Shipments == other.Shipments ||
                    Shipments != null &&
                    Shipments.SequenceEqual(other.Shipments)
                );
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RateShipmentsRequest {\n");
            sb.Append("  ShipmentIds: ").Append(ShipmentIds).Append("\n");
            sb.Append("  RateOptions: ").Append(RateOptions).Append("\n");
            sb.Append("  Shipments: ").Append(Shipments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as RateShipmentsRequest);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (ShipmentIds != null)
                {
                    hash = hash * 59 + ShipmentIds.GetHashCode();
                }
                if (RateOptions != null)
                {
                    hash = hash * 59 + RateOptions.GetHashCode();
                }
                if (Shipments != null)
                {
                    hash = hash * 59 + Shipments.GetHashCode();
                }
                return hash;
            }
        }
    }
}