/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    ///     RateShipmentRequest
    /// </summary>
    [DataContract]
    public class RateShipmentRequest : IEquatable<RateShipmentRequest>, IValidatableObject
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RateShipmentRequest" /> class.
        /// </summary>
        /// <param name="shipmentId">ShipmentId.</param>
        /// <param name="shipment">Shipment.</param>
        /// <param name="rateOptions">RateOptions.</param>
        public RateShipmentRequest(string shipmentId = default(string),
            AddressValidatingShipment shipment = default(AddressValidatingShipment),
            RateRequest rateOptions = default(RateRequest))
        {
            ShipmentId = shipmentId;
            Shipment = shipment;
            RateOptions = rateOptions;
        }

        /// <summary>
        ///     Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name = "shipment_id", EmitDefaultValue = false)]
        public string ShipmentId { get; set; }

        /// <summary>
        ///     Gets or Sets Shipment
        /// </summary>
        [DataMember(Name = "shipment", EmitDefaultValue = false)]
        public AddressValidatingShipment Shipment { get; set; }

        /// <summary>
        ///     Gets or Sets RateOptions
        /// </summary>
        [DataMember(Name = "rate_options", EmitDefaultValue = false)]
        public RateRequest RateOptions { get; set; }

        /// <summary>
        ///     Returns true if RateShipmentRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of RateShipmentRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RateShipmentRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
            {
                return false;
            }

            return
                (
                    ShipmentId == other.ShipmentId ||
                    ShipmentId != null &&
                    ShipmentId.Equals(other.ShipmentId)
                ) &&
                (
                    Equals(Shipment, other.Shipment) ||
                    Shipment != null &&
                    Shipment.Equals(other.Shipment)
                ) &&
                (
                    Equals(RateOptions, other.RateOptions) ||
                    RateOptions != null &&
                    RateOptions.Equals(other.RateOptions)
                );
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RateShipmentRequest {\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  Shipment: ").Append(Shipment).Append("\n");
            sb.Append("  RateOptions: ").Append(RateOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as RateShipmentRequest);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (ShipmentId != null)
                {
                    hash = hash * 59 + ShipmentId.GetHashCode();
                }
                if (Shipment != null)
                {
                    hash = hash * 59 + Shipment.GetHashCode();
                }
                if (RateOptions != null)
                {
                    hash = hash * 59 + RateOptions.GetHashCode();
                }
                return hash;
            }
        }
    }
}