/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ShipEngine.ApiClient.Client;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing RatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RatesApiTests
    {
        private RatesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RatesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RatesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RatesApi
            //Assert.IsInstanceOfType(typeof(RatesApi), instance, "instance is a RatesApi");
        }

        
        /// <summary>
        /// Test RatesEstimate
        /// </summary>
        [Test]
        public void RatesEstimateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RateEstimateRequest estimateRequest = null;
            //string apiKey = null;
            //var response = instance.RatesEstimate(estimateRequest, apiKey);
            //Assert.IsInstanceOf<List<Rate>> (response, "response is List<Rate>");
        }
        
        /// <summary>
        /// Test RatesGet
        /// </summary>
        [Test]
        public void RatesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rateId = null;
            //string apiKey = null;
            //var response = instance.RatesGet(rateId, apiKey);
            //Assert.IsInstanceOf<Rate> (response, "response is Rate");
        }
        
        /// <summary>
        /// Test RatesRateShipment
        /// </summary>
        [Test]
        public void RatesRateShipmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RateShipmentRequest request = null;
            //string apiKey = null;
            //instance.RatesRateShipment(request, apiKey);
            
        }
        
        /// <summary>
        /// Test RatesRateShipmentsAsync
        /// </summary>
        [Test]
        public void RatesRateShipmentsAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RateShipmentsRequest request = null;
            //string apiKey = null;
            //instance.RatesRateShipmentsAsync(request, apiKey);
            
        }
        
    }

}
