/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing CustomsItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomsItemTests
    {
        // TODO uncomment below to declare an instance variable for CustomsItem
        //private CustomsItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomsItem
            //instance = new CustomsItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomsItem
        /// </summary>
        [Test]
        public void CustomsItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomsItem
            //Assert.IsInstanceOfType<CustomsItem> (instance, "variable 'instance' is a CustomsItem");
        }


        /// <summary>
        /// Test the property 'CustomsItemId'
        /// </summary>
        [Test]
        public void CustomsItemIdTest()
        {
            // TODO unit test for the property 'CustomsItemId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'HarmonizedTariffCode'
        /// </summary>
        [Test]
        public void HarmonizedTariffCodeTest()
        {
            // TODO unit test for the property 'HarmonizedTariffCode'
        }
        /// <summary>
        /// Test the property 'CountryOfOrigin'
        /// </summary>
        [Test]
        public void CountryOfOriginTest()
        {
            // TODO unit test for the property 'CountryOfOrigin'
        }

    }

}
