/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing RateEstimateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RateEstimateRequestTests
    {
        // TODO uncomment below to declare an instance variable for RateEstimateRequest
        //private RateEstimateRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RateEstimateRequest
            //instance = new RateEstimateRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RateEstimateRequest
        /// </summary>
        [Test]
        public void RateEstimateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RateEstimateRequest
            //Assert.IsInstanceOfType<RateEstimateRequest> (instance, "variable 'instance' is a RateEstimateRequest");
        }


        /// <summary>
        /// Test the property 'CarrierId'
        /// </summary>
        [Test]
        public void CarrierIdTest()
        {
            // TODO unit test for the property 'CarrierId'
        }
        /// <summary>
        /// Test the property 'FromCountryCode'
        /// </summary>
        [Test]
        public void FromCountryCodeTest()
        {
            // TODO unit test for the property 'FromCountryCode'
        }
        /// <summary>
        /// Test the property 'FromPostalCode'
        /// </summary>
        [Test]
        public void FromPostalCodeTest()
        {
            // TODO unit test for the property 'FromPostalCode'
        }
        /// <summary>
        /// Test the property 'ToCountryCode'
        /// </summary>
        [Test]
        public void ToCountryCodeTest()
        {
            // TODO unit test for the property 'ToCountryCode'
        }
        /// <summary>
        /// Test the property 'ToPostalCode'
        /// </summary>
        [Test]
        public void ToPostalCodeTest()
        {
            // TODO unit test for the property 'ToPostalCode'
        }
        /// <summary>
        /// Test the property 'ToCityLocality'
        /// </summary>
        [Test]
        public void ToCityLocalityTest()
        {
            // TODO unit test for the property 'ToCityLocality'
        }
        /// <summary>
        /// Test the property 'ToStateProvince'
        /// </summary>
        [Test]
        public void ToStateProvinceTest()
        {
            // TODO unit test for the property 'ToStateProvince'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Test]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }
        /// <summary>
        /// Test the property 'Confirmation'
        /// </summary>
        [Test]
        public void ConfirmationTest()
        {
            // TODO unit test for the property 'Confirmation'
        }
        /// <summary>
        /// Test the property 'AddressResidentialIndicator'
        /// </summary>
        [Test]
        public void AddressResidentialIndicatorTest()
        {
            // TODO unit test for the property 'AddressResidentialIndicator'
        }
        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Test]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }

    }

}
