/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing RateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RateResponseTests
    {
        // TODO uncomment below to declare an instance variable for RateResponse
        //private RateResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RateResponse
            //instance = new RateResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RateResponse
        /// </summary>
        [Test]
        public void RateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RateResponse
            //Assert.IsInstanceOfType<RateResponse> (instance, "variable 'instance' is a RateResponse");
        }


        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }
        /// <summary>
        /// Test the property 'InvalidRates'
        /// </summary>
        [Test]
        public void InvalidRatesTest()
        {
            // TODO unit test for the property 'InvalidRates'
        }
        /// <summary>
        /// Test the property 'RateRequestId'
        /// </summary>
        [Test]
        public void RateRequestIdTest()
        {
            // TODO unit test for the property 'RateRequestId'
        }
        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Test]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
